### ISSUE TITLE
Request: File dialog to remember last used folder

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#343]
this is very annoying. every time i do open, save, export the file dialog goes to anywhere.
also if it could use KDE dialogs instead of gnome one it would make me super happy.

**Comment by guillaumechereau** [comment]
I pushed some changes to use the tinyfiledialogs library instead of my own code for open dialogs.  Not tested much yet, but normally it should use KDE dialogs on KDE systems.

**Comment by jerobarraco** [comment]
I'll test it asap if the build has been created in the actions

**Comment by jerobarraco** [comment]
It works! It's amazing! Thanks :)
The only thing that doesn't quite work is the last folder used.
When using Open it always goes to the working directory of goxel (~/bin in my case)
![image](https://github.com/guillaumechereau/goxel/assets/3729895/22e7858a-138b-45df-8698-0a7f6320ce26)

when calling SaveAs it does sets the directory of the original asset
![image](https://github.com/guillaumechereau/goxel/assets/3729895/bd0694b2-e9a9-4ce6-8655-d2be204e113e)

but if i create a new file and click Save it goes back to ~/bin again
![image](https://github.com/guillaumechereau/goxel/assets/3729895/cc3b71f9-3fbe-4f0f-b50d-a71e8a562f8a)

**Comment by vareille** [comment]
Hi, I've just implemented the correct behaviour for kdialog in tinyfiledialogs.
it's in version 3.17
Give it a try

**Comment by jerobarraco** [comment]
Thanks, i just tried action 200 but still the same problem
steps:
1. open image
2. save as : Dialog is correct folder
3. Use menu to create new 
4. Save As: dialog is wrong folder (~/bin). Expected: last used folder.

it would be even better if it could remember the last used folder even after reboots.

**Comment by jerobarraco** [comment]
i've made a stub proposal for what i want. notice this is not amazing since it won't remember the folder after closing the software but it's certainly much better than now.
also i've edited the code on github so it may not compile or may crash.
https://github.com/guillaumechereau/goxel/compare/master...jerobarraco:goxel:patch-1

**Comment by vareille** [comment]
Can you contact me directly on my email (at the top of the header file)
how are you calling tinyfd_saveFileDialog() exactly ?

**Comment by vareille** [comment]
on this github repo, you are using v3.16.2
make sure you use 3.17 (and better)

how are you calling tinyfd_saveFileDialog() exactly ?
what are you passing as aDefaultPathAndOrFile ?

**Comment by guillaumechereau** [comment]
I updated to the last version on tinyfiledialog now.  This code is currently quite messy in goxel, but currently the logic is:

if we have a current goxel file with a known saved path, we pass the pass to both tinyfd_saveFileDialog and tinyfd_openFileDialog.  If we don't have a current file, we pass "untitled.gox" to save and NULL to open.

What I am not sure about: if we just pass a file name (not a path) to tinyfd_saveFileDialog, will it still attempt to move to the last used directory?

**Comment by vareille** [comment]
set

    tinyfd_versbose =  1;

and launch your aplication from a command line. it will output the cammand line call that tinyfiledialogs is using. Let's see what it says.

**Comment by guillaumechereau** [comment]
I pushed a few more changes regarding this issue.  Only tested a bit on Mac so far.

**Comment by vareille** [comment]
Nobody here has confirmed that tinyfiledialogs v3.17 doesn't use the last folder :
- jerobarraco seems to have tested v3.16 (which didn't have the last folder feature implemented)
- guillaumechereau has updated this project with tinyfiledialogs v3.17.x didn't try the last folder feature.

**Comment by guillaumechereau** [comment]
I don’t have much time right now, but as far as I could tell it worked fine
in last commit.  I’ll test it more before the next release to ensure there
are no corner cases on all desktop platform.  On a side note Goxel should
now save the list of recently used files so that’s another way to simplify
reopening previously used files.

**Comment by jerobarraco** [comment]
where can i obtain 3.17? @vareille

**Comment by jerobarraco** [comment]
i've just tried build 204 and it works as desired! thanks a lot! 
it even remembers the directory across reboots!
Awesome!

**Comment by guillaumechereau** [comment]
OK I'll close this for now then.
